veronicagr/talent-fast

index.html
=> subindo html semnantico

package.json
Instalação Express Server / Instalação Validador-cpf npm / npm init
=> Instalação Express Server / Instalação Validador-cpf npm / npm init

index.html
=> Subindo o CDN do pages.js

dist/style.css, index.html
estilo e alterações index.html
=> estilo e alterações index.html

dist/js/templates.js, dist/style.css, index.html
=> alteração template index

dist/style.css
=> alteração background

dist/js/app.js, dist/js/script.js, dist/js/templates.js, index.html
=> Formatação dos formulários

dist/js/app.js, dist/js/templates.js, index.html, package-lock.json, package.json
=> mask foi alterado

dist/js/templates.js
=> layout form novo

dist/js/templates.js, dist/style.css, index.html
=> layout encaminhado

dist/js/app.js, dist/js/templates.js
mudança de button para a, validação do cpf
=> mudança de button para a, validação do cpf

dist/js/templates.js, package-lock.json
inclusão input select estado civil
=> inclusão input select estado civil

dist/js/script.js, dist/js/templates.js
Adicionando um novo formulário, padronização dos botoes
=> Adicionando um novo formulário, padronização dos botoes

dist/js/templates.js, dist/style.css
consertando máscara cep e telefone
=> consertando máscara cep e telefone

dist/js/script.js, dist/js/templates.js, dist/style.css
=> consertando conflitos

dist/js/script.js, dist/js/templates.js, dist/style.css
login func e alterações botões
=> login func e alterações botões

dist/js/app.js, firebase-config.js, index.html
=> correção conflito firebase

dist/js/script.js, dist/js/templates.js
=> finalização cadastro

dist/js/app.js, dist/js/script.js, dist/js/templates.js
=> layout e login

dist/js/app.js, dist/js/templates.js, dist/style.css
=> conflitinho

dist/js/app.js, dist/js/templates.js, dist/style.css
=> mensagem pós-cadastro e login

dist/js/app.js, dist/js/templates.js
estilização tela de contas recusadas
=> estilização tela de contas recusadas
